# Generated by Django 6.0.4 on 2026-04-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSITUweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
